apiVersion: v1
kind: Namespace
metadata:
  name: testns
  annotations: 
    rbac-sync.nais.io/group-name: test@nav.no
    rbac-sync.nais.io/role-name: teammember
    rbac-sync.nais.io/rolebinding-name: teammembers
