---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbac-sync-account
  namespace: nais

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: rbac-sync-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: rbac-sync-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rbac-sync-role
subjects:
- kind: ServiceAccount
  name: rbac-sync-account
  namespace: nais

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rbac-sync
  namespace: nais
spec:
  replicas: 1
  template:
    metadata:
      name: rbac-sync
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
      labels:
        app: rbac-sync
    spec:
      serviceAccountName: rbac-sync-account
      containers:
      - name: rbac-sync
        image: navikt/rbac-sync
        imagePullPolicy: Always
        args:
        - '-update-interval=10m'
        - '-gcp-admin-user=sten.ivar.rokke@nav.no'
        - '-serviceaccount-keyfile=/secrets/credentials.json'
        - '-bind-address=:8080'
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        resources:
            requests:
                cpu: 0
                memory: 10Mi
            limits:
                cpu: 0.1
                memory: 50Mi
        volumeMounts:
        - name: nais-iam-secret
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: nais-iam-secret
        secret:
          secretName: nais-iam-secret
          items:
          - key: credentials.json
            path: credentials.json
